### ISSUE TITLE
[Epic] As a new and/or busy university student, I can obtain faculty locations and possible meeting locations easily.

### ISSUE THREAD

**Issue by kaitingpeck** [CS2103-AY1819S1-W13-2/main#50]
V1.4:
1. As a new university student, I can find my contact's faculty location visually on a map as I am not familiar with the campus.
2. As a busy university student, I can quickly obtain a possible meeting location for an event or a meeting to save myself time and energy thinking about such a minor detail.

V2.0:
- As a considerate university student, I can obtain a free time period that works for all contacts in a group so that I can find a suitable time for an event or meeting.
- As a considerate university student, I can obtain a meeting location that is suitable for all contacts in a group (based on faculty) so that I can find a convenient location for an event or meeting (building on point 2 in v1.4).

**Comment by pratyayj** [comment]
This feature has been developed across multiple PRs so far: #186, #176, #144, #140, #134, #132, #75.

**Comment by pratyayj** [comment]
PR #191 has added tests and added Javadocs.
